/**
 * ABI → normalized function definitions.
 * Generated by Unzap — do not edit manually.
 *
 * Import WRITE_FUNCTIONS / READ_FUNCTIONS to render the UI generically.
 * Swap lib/contract.ts when targeting a different contract.
 */

import { shortString } from 'starknet';
import { ABI } from './contract';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface FunctionParam {
  name: string;
  cairoType: string;
  label: string;
  inputType: 'text' | 'number';
  placeholder: string;
}

export interface ContractFunction {
  name: string;
  title: string;
  params: FunctionParam[];
  outputType: string;
  isWrite: boolean;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export function toTitle(s: string): string {
  return s.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function toInputType(cairoType: string): 'text' | 'number' {
  const numTypes = ['u8', 'u16', 'u32', 'u64', 'u128', 'u256', 'i8', 'i16', 'i32', 'i64'];
  if (numTypes.some((t) => cairoType.includes(t))) return 'number';
  return 'text';
}

function toPlaceholder(cairoType: string): string {
  if (cairoType.includes('ContractAddress')) return '0x...';
  if (cairoType.includes('bool')) return 'true / false';
  if (cairoType.includes('u') || cairoType.includes('i')) return 'e.g. 0';
  return 'Value';
}

export function formatResult(raw: string, cairoType: string): string {
  if (raw === null || raw === undefined || raw === '') return '—';
  
  if (cairoType === 'core::bool' || cairoType === 'bool') {
    return raw === '0x1' || raw === '1' ? 'Yes' : 'No';
  }

  if (cairoType.includes('felt252')) {
    try {
      if (raw.startsWith('0x')) {
        const decoded = shortString.decodeShortString(raw);
        if (decoded && /^[\x20-\x7E]*$/.test(decoded) && decoded.length > 0) {
          return decoded;
        }
      }
    } catch {
      // Fall through to default formatting
    }
  }

  if (cairoType.includes('ContractAddress')) {
    if (raw.length > 18) return `${raw.slice(0, 10)}…${raw.slice(-6)}`;
    return raw;
  }

  try {
    return BigInt(raw).toString();
  } catch {
    return raw;
  }
}

/**
 * Normalizes user-provided string arguments into a raw Starknet calldata array.
 * Supports splitting u256 types into [low, high] felts.
 */
export function prepareCalldata(fn: ContractFunction, args: string[]): string[] {
  const calldata: string[] = [];

  fn.params.forEach((param, idx) => {
    const val = args[idx] ?? '';
    if (param.cairoType.includes('u256')) {
      try {
        const bn = BigInt(val);
        const low = (bn & ((BigInt(1) << BigInt(128)) - BigInt(1))).toString();
        const high = (bn >> BigInt(128)).toString();
        calldata.push(low, high);
      } catch {
        calldata.push(val, '0'); // Fallback
      }
    } else {
      calldata.push(val);
    }
  });

  return calldata;
}

// ── Parsed functions ──────────────────────────────────────────────────────────

export const CONTRACT_FUNCTIONS: ContractFunction[] = (() => {
  const fns: any[] = [];
  
  (ABI as unknown as any[]).forEach((item) => {
    if (item.type === 'function') {
      fns.push(item);
    } else if (item.type === 'interface' && Array.isArray(item.items)) {
      item.items.forEach((inner: any) => {
        if (inner.type === 'function') {
          fns.push(inner);
        }
      });
    }
  });

  return fns.map((fn) => ({
    name: fn.name as string,
    title: toTitle(fn.name as string),
    isWrite: fn.state_mutability === 'external',
    outputType: (fn.outputs?.[0]?.type as string) ?? 'void',
    params: ((fn.inputs ?? []) as any[]).map((i: any) => ({
      name: i.name as string,
      cairoType: i.type as string,
      label: toTitle(i.name as string),
      inputType: toInputType(i.type as string),
      placeholder: toPlaceholder(i.type as string),
    })),
  }));
})();

export const WRITE_FUNCTIONS = CONTRACT_FUNCTIONS.filter((f) => f.isWrite);
export const READ_FUNCTIONS = CONTRACT_FUNCTIONS.filter((f) => !f.isWrite);
