// Generated by Unzap Contract Lab — https://unzap.dev
// Re-generate from Contract Lab if the ABI changes.

export const CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS ?? "{{ADDRESS}}";

export const CLASS_HASH = "{{CLASS_HASH}}";
export const NETWORK = "{{NETWORK}}" as "mainnet" | "sepolia";

export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL ?? "{{RPC_URL}}";

export const ABI = {{ABI_JSON}} as const;

// ── Derived ───────────────────────────────────────────────────────────────────

export const NETWORK_LABEL =
  NETWORK === "mainnet" ? "Starknet Mainnet" : "Starknet Sepolia";

export const EXPLORER_URL =
  NETWORK === "mainnet" ? "https://starkscan.co" : "https://sepolia.starkscan.co";

export function explorerTxUrl(hash: string): string {
  return `${EXPLORER_URL}/tx/${hash}`;
}

