// Generated by Unzap Contract Lab — https://unzap.dev
// Re-generate from Contract Lab if the ABI changes.

export const CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS ?? "{{ADDRESS}}";

export const CLASS_HASH = "{{CLASS_HASH}}";
export const NETWORK = "{{NETWORK}}" as const;

export const RPC_URL = "{{RPC_URL}}";

export const ABI = {{ABI_JSON}} as const;
