'use client';

/**
 * Generic contract interaction hooks — generated by Unzap.
 *
 * useContractRead  — calls any view function by entrypoint name.
 * useContractWrite — executes any external function by entrypoint name.
 *
 * Both hooks work against any ABI.  Swap lib/contract.ts to target a
 * different contract — no changes needed here.
 */

import { useState, useCallback, useEffect, useRef } from 'react';
import { RpcProvider, Account } from 'starknet';
import { CONTRACT_ADDRESS, RPC_URL } from '@/lib/contract';
import { useWallet } from '@/hooks/wallet';
import { prepareCalldata, type ContractFunction } from '@/lib/contractFunctions';

// ── Read ──────────────────────────────────────────────────────────────────────

export function useContractRead(fn: ContractFunction, args: string[]) {
  const [data, setData] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const provider = useMemo(() => new RpcProvider({ nodeUrl: RPC_URL }), []);

  const argsRef = useRef<string[]>(args);
  argsRef.current = args;

  const read = useCallback(async (): Promise<string | null> => {
    const currentArgs = argsRef.current;
    if (currentArgs.some((a) => a.trim() === '')) return null;
    setLoading(true);
    setError(null);
    try {
      const normalizedCalldata = prepareCalldata(fn, currentArgs);
      
      const response = await provider.callContract({
        contractAddress: CONTRACT_ADDRESS,
        entrypoint: fn.name,
        calldata: normalizedCalldata,
      });
      const raw = Array.isArray(response)
        ? response[0]
        : (response as any).result?.[0] ?? String(response);
      const rawStr = String(raw);
      setData(rawStr);
      return rawStr;
    } catch (e: any) {
      setError(e.message || String(e));
      return null;
    } finally {
      setLoading(false);
    }
  }, [fn, provider]);

  // Auto-fetch parameterless functions once on mount
  useEffect(() => {
    if (fn.params.length === 0) {
      void read();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return { data, loading, error, refetch: read };
}

// ── Write ─────────────────────────────────────────────────────────────────────

export function useContractWrite(fn: ContractFunction) {
  const { account, szWallet, walletType } = useWallet();
  const [status, setStatus] = useState<'idle' | 'pending' | 'success' | 'error'>('idle');
  const [txHash, setTxHash] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const provider = useMemo(() => new RpcProvider({ nodeUrl: RPC_URL }), []);

  const execute = useCallback(
    async (args: string[]): Promise<string> => {
      if (!account) throw new Error('Wallet not connected.');
      setStatus('pending');
      setError(null);
      setTxHash(null);

      const normalizedCalldata = prepareCalldata(fn, args);
      const calls = [{ contractAddress: CONTRACT_ADDRESS, entrypoint: fn.name, calldata: normalizedCalldata }];
      let hash = '';

      try {
        if (walletType === 'privy' && szWallet) {
          // Gasless via StarkZap (Privy embedded wallet)
          const tx = await szWallet.execute(calls, { feeMode: 'sponsored' });
          hash = tx.hash;
          setTxHash(hash);
          await tx.wait();
        } else {
          // Standard extension wallet execution
          const result = await (account as Account).execute(calls);
          hash = result.transaction_hash;
          setTxHash(hash);
          await provider.waitForTransaction(hash);
        }
        setStatus('success');
        return hash;
      } catch (e) {
        setStatus('error');
        const msg = e instanceof Error ? e.message : String(e);
        setError(msg);
        throw e;
      }
    },
    [account, szWallet, walletType, fn, provider]
  );

  const reset = useCallback(() => {
    setStatus('idle');
    setTxHash(null);
    setError(null);
  }, []);

  return { execute, status, txHash, error, reset };
}
