import type { Metadata } from "next";
import { StarkzapProvider } from "@/hooks/use{{PASCAL_NAME}}";
import "./globals.css";

export const metadata: Metadata = {
  title: "{{CONTRACT_NAME}}",
  description: "Generated by Unzap Contract Lab",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/*
          StarkzapProvider manages a single wallet instance shared across all
          write hooks. Do not move this — it must wrap the entire app.
        */}
        <StarkzapProvider>{children}</StarkzapProvider>
      </body>
    </html>
  );
}
