/**
 * Next.js (App Router) + Tailwind v4 project template generators.
 * Every function returns file content as a string — no template files, no engines.
 *
 * Design language: developer tool, not a SaaS dashboard.
 * References: VS Code, terminal UIs, browser devtools.
 * - Dark #0a0a0a background
 * - Flat panels with #1e1e1e borders (no card shadows, minimal radius)
 * - Monospace for all identifiers, values, addresses
 * - Dense information layout — no oversized headings or hero text
 */

import type { AbiEntry } from "@/app/studio/contract-lab/types";
import type { ParsedAbi } from "../abiParser";

// ── naming helpers ─────────────────────────────────────────────────────────────

function toPascal(s: string): string {
  return s.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase());
}
function toCamel(s: string): string {
  const p = toPascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}
function shortType(t: string): string {
  return t.split("::").pop()?.replace(/<.*>$/, "") ?? t;
}

// ── package.json ───────────────────────────────────────────────────────────────

export function generatePackageJson(contractName: string): string {
  const slug = contractName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return JSON.stringify(
    {
      name: `${slug}-app`,
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "^15.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        starknet: "^9.0.0",
        starkzap: "^2.0.0",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4.0.0",
        "@types/node": "^20.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        postcss: "^8.0.0",
        tailwindcss: "^4.0.0",
        typescript: "^5.0.0",
      },
    },
    null,
    2
  );
}

// ── postcss.config.mjs ─────────────────────────────────────────────────────────

export function generatePostcssConfig(): string {
  return `/** @type {import('postcss-load-config').Config} */
const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
`;
}

// ── app/globals.css ────────────────────────────────────────────────────────────

export function generateGlobalsCss(): string {
  return `@import "tailwindcss";

:root {
  color-scheme: dark;
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

html,
body {
  height: 100%;
  margin: 0;
  padding: 0;
  background: #0a0a0a;
  color: #d4d4d8;
  font-family: system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
  font-size: 13px;
}

/* Scrollbar — subtle, IDE-style */
::-webkit-scrollbar { width: 6px; height: 6px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }
::-webkit-scrollbar-thumb:hover { background: #3a3a3a; }

input[type="text"],
input[type="number"],
textarea {
  font-family: ui-monospace, "Cascadia Code", "JetBrains Mono", monospace;
}
`;
}

// ── tsconfig.json ──────────────────────────────────────────────────────────────

export function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

// ── .env.example ───────────────────────────────────────────────────────────────

export function generateEnvExample(
  contractAddress: string,
  network: string
): string {
  return `# Copy to .env.local — already pre-filled with your deployed contract.
NEXT_PUBLIC_CONTRACT_ADDRESS="${contractAddress}"
NEXT_PUBLIC_NETWORK="${network}"
`;
}

// ── lib/contract.ts ────────────────────────────────────────────────────────────

export function generateContractLib(
  contractAddress: string,
  classHash: string,
  network: string,
  abi: AbiEntry[]
): string {
  const rpc =
    network === "mainnet"
      ? "https://free-rpc.nethermind.io/mainnet-juno/v0_8"
      : "https://free-rpc.nethermind.io/sepolia-juno/v0_8";
  return `// Generated by Unzap Contract Lab — https://unzap.dev
// Re-generate from Contract Lab if the ABI changes.

export const CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS ?? "${contractAddress}";

export const CLASS_HASH = "${classHash}";
export const NETWORK = "${network}" as const;
export const RPC_URL = "${rpc}";

export const ABI = ${JSON.stringify(abi, null, 2)} as const;
`;
}

// ── app/layout.tsx ─────────────────────────────────────────────────────────────

export function generateLayout(contractName: string): string {
  const pascal = toPascal(contractName);
  return `import type { Metadata } from "next";
import { StarkzapProvider } from "@/hooks/use${pascal}";
import "./globals.css";

export const metadata: Metadata = {
  title: "${contractName}",
  description: "Generated by Unzap Contract Lab",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/*
          StarkzapProvider manages a single wallet instance shared across all
          write hooks. Do not move this — it must wrap the entire app.
        */}
        <StarkzapProvider>{children}</StarkzapProvider>
      </body>
    </html>
  );
}
`;
}

// ── components/LogsPanel.tsx ───────────────────────────────────────────────────
// Terminal-style output panel. Lives at the bottom of the layout.
// Receives log entries from page.tsx via props — no global state.

export function generateLogsPanel(): string {
  return `"use client";

import { useEffect, useRef } from "react";

export type LogType = "call" | "result" | "tx" | "error" | "info";

export interface LogEntry {
  id: string;
  type: LogType;
  text: string;
  timestamp: number;
}

const PREFIX: Record<LogType, string> = {
  call:   ">",
  result: "←",
  tx:     "⚡",
  error:  "✗",
  info:   "·",
};

const COLOR: Record<LogType, string> = {
  call:   "#71717a", // zinc-500
  result: "#d4d4d8", // zinc-300
  tx:     "#f59e0b", // amber-500
  error:  "#f87171", // red-400
  info:   "#3f3f46", // zinc-700
};

function timestamp(ms: number): string {
  const d = new Date(ms);
  return [d.getHours(), d.getMinutes(), d.getSeconds()]
    .map((n) => String(n).padStart(2, "0"))
    .join(":");
}

interface LogsPanelProps {
  logs: LogEntry[];
  onClear: () => void;
}

export function LogsPanel({ logs, onClear }: LogsPanelProps) {
  const bottomRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to latest entry
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs.length]);

  return (
    <div
      style={{
        borderTop: "1px solid #1e1e1e",
        backgroundColor: "#080808",
        height: "160px",
        display: "flex",
        flexDirection: "column",
        flexShrink: 0,
      }}
    >
      {/* Panel header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "4px 16px",
          borderBottom: "1px solid #161616",
          flexShrink: 0,
        }}
      >
        <span
          style={{
            fontFamily: "ui-monospace, monospace",
            fontSize: "10px",
            textTransform: "uppercase",
            letterSpacing: "0.12em",
            color: "#3f3f46",
          }}
        >
          output
        </span>
        {logs.length > 0 && (
          <button
            onClick={onClear}
            style={{
              fontFamily: "ui-monospace, monospace",
              fontSize: "10px",
              color: "#3f3f46",
              background: "none",
              border: "none",
              cursor: "pointer",
              padding: "0",
            }}
            onMouseEnter={(e) =>
              ((e.target as HTMLButtonElement).style.color = "#71717a")
            }
            onMouseLeave={(e) =>
              ((e.target as HTMLButtonElement).style.color = "#3f3f46")
            }
          >
            clear
          </button>
        )}
      </div>

      {/* Log entries */}
      <div
        style={{
          flex: 1,
          overflowY: "auto",
          padding: "6px 16px",
        }}
      >
        {logs.length === 0 ? (
          <p
            style={{
              fontFamily: "ui-monospace, monospace",
              fontSize: "11px",
              color: "#2d2d2d",
              margin: 0,
            }}
          >
            No activity yet.
          </p>
        ) : (
          logs.map((entry) => (
            <div
              key={entry.id}
              style={{
                display: "flex",
                alignItems: "baseline",
                gap: "8px",
                marginBottom: "2px",
                fontFamily: "ui-monospace, monospace",
                fontSize: "11px",
                lineHeight: "1.6",
              }}
            >
              <span style={{ color: COLOR[entry.type], flexShrink: 0, width: "12px" }}>
                {PREFIX[entry.type]}
              </span>
              <span style={{ color: COLOR[entry.type], flex: 1, wordBreak: "break-all" }}>
                {entry.text}
              </span>
              <span style={{ color: "#2d2d2d", flexShrink: 0, fontSize: "10px" }}>
                {timestamp(entry.timestamp)}
              </span>
            </div>
          ))
        )}
        <div ref={bottomRef} />
      </div>
    </div>
  );
}
`;
}

// ── app/page.tsx ───────────────────────────────────────────────────────────────
// Owns: layout skeleton, TopBar, wallet state, log accumulation.
// Delegates: contract interaction to ContractUI, log display to LogsPanel.

export function generatePage(
  contractName: string,
  network: string,
  contractAddress: string
): string {
  const pascal = toPascal(contractName);
  const shortAddr = contractAddress
    ? `${contractAddress.slice(0, 8)}…${contractAddress.slice(-6)}`
    : "0x…";

  return `"use client";

import { useState, useCallback } from "react";
import { useStarkzap } from "@/hooks/use${pascal}";
import { ContractUI } from "@/components/ContractUI";
import { LogsPanel, type LogEntry } from "@/components/LogsPanel";

// ── TopBar ────────────────────────────────────────────────────────────────────
// IDE-style header. Wallet connection lives here, not in ContractUI.
// ContractUI only reads wallet state — it never initiates connection.

function TopBar() {
  const { address, connectWallet } = useStarkzap();

  return (
    <div
      style={{
        height: "36px",
        borderBottom: "1px solid #1e1e1e",
        backgroundColor: "#0d0d0d",
        display: "flex",
        alignItems: "center",
        padding: "0 16px",
        gap: "12px",
        flexShrink: 0,
      }}
    >
      {/* Left: contract identity */}
      <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "12px", color: "#d4d4d8", fontWeight: 500 }}>
        ${contractName}
      </span>

      <span style={{ color: "#2a2a2a" }}>·</span>

      <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "11px", color: "#52525b" }}>
        ${network}
      </span>

      <span style={{ color: "#2a2a2a" }}>·</span>

      <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "11px", color: "#52525b" }}>
        ${shortAddr}
      </span>

      <span style={{ color: "#2a2a2a" }}>·</span>

      {/* Live status indicator */}
      <span style={{ display: "flex", alignItems: "center", gap: "5px" }}>
        <span
          style={{
            width: "6px",
            height: "6px",
            borderRadius: "50%",
            backgroundColor: "#4ade80",
            boxShadow: "0 0 6px rgba(74,222,128,0.5)",
          }}
        />
        <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#4ade8066", letterSpacing: "0.05em" }}>
          live
        </span>
      </span>

      {/* Right: wallet */}
      <div style={{ marginLeft: "auto" }}>
        {address ? (
          <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
            <span style={{ width: "5px", height: "5px", borderRadius: "50%", backgroundColor: "#4ade80" }} />
            <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "11px", color: "#71717a" }}>
              {address.slice(0, 10)}&hellip;{address.slice(-4)}
            </span>
          </div>
        ) : (
          <button
            onClick={connectWallet}
            style={{
              fontFamily: "ui-monospace, monospace",
              fontSize: "11px",
              color: "#f59e0b",
              background: "none",
              border: "1px solid #292215",
              borderRadius: "4px",
              padding: "3px 10px",
              cursor: "pointer",
              transition: "border-color 0.15s, color 0.15s",
            }}
            onMouseEnter={(e) => {
              const btn = e.currentTarget;
              btn.style.borderColor = "#78450c";
              btn.style.color = "#fbbf24";
            }}
            onMouseLeave={(e) => {
              const btn = e.currentTarget;
              btn.style.borderColor = "#292215";
              btn.style.color = "#f59e0b";
            }}
          >
            connect wallet
          </button>
        )}
      </div>
    </div>
  );
}

// ── page ──────────────────────────────────────────────────────────────────────

export default function Home() {
  const [logs, setLogs] = useState<LogEntry[]>([]);

  const addLog = useCallback(
    (entry: Omit<LogEntry, "id" | "timestamp">) => {
      setLogs((prev) => [
        ...prev.slice(-199),
        { ...entry, id: Math.random().toString(36).slice(2), timestamp: Date.now() },
      ]);
    },
    []
  );

  const clearLogs = useCallback(() => setLogs([]), []);

  return (
    <div style={{ height: "100vh", display: "flex", flexDirection: "column", backgroundColor: "#0a0a0a", overflow: "hidden" }}>
      <TopBar />

      <main style={{ flex: 1, overflowY: "auto" }}>
        <div style={{ maxWidth: "680px", margin: "0 auto", padding: "24px 20px" }}>
          <ContractUI onLog={addLog} />
        </div>
      </main>

      <LogsPanel logs={logs} onClear={clearLogs} />
    </div>
  );
}
`;
}

// ── components/ContractUI.tsx ──────────────────────────────────────────────────
// Design rules:
//   - Flat rows with border-b dividers, NOT individual cards
//   - Monospace for all fn names, types, values
//   - No large headings, no padding bloat
//   - Section group labels (READ / WRITE) are tiny uppercase strips
//   - ONE wallet hint above the write group — not repeated per function
//   - Tooltip on disabled execute buttons via CSS :hover

function buildReadSection(fn: AbiEntry, contractName: string): string {
  const pascal = toPascal(contractName);
  const hook = `use${pascal}${toPascal(fn.name)}`;
  const hasParams = !!fn.inputs?.length;

  const stateDecls = hasParams
    ? fn.inputs!
        .map(
          (i) => `  const [${toCamel(i.name)}, set${toPascal(i.name)}] = useState("");`
        )
        .join("\n")
    : "";

  const hookCall = hasParams
    ? fn.inputs!.map((i) => toCamel(i.name)).join(", ")
    : "";

  // For logging: track loading transitions to log results
  const logSetup = `
  const userFetchRef = useRef(false);
  const prevLoadingRef = useRef(false);

  const handleRefetch = useCallback(() => {
    userFetchRef.current = true;
    log({ type: "call", text: "${fn.name}(${fn.inputs?.map((i) => `\${${toCamel(i.name)}}`).join(", ") ?? ""})" });
    refetch();
  }, [refetch, ${hasParams ? fn.inputs!.map((i) => toCamel(i.name)).join(", ") + ", " : ""}log]);

  useEffect(() => {
    if (!userFetchRef.current) return;
    if (prevLoadingRef.current && !loading) {
      userFetchRef.current = false;
      if (data !== null && data !== undefined) {
        log({ type: "result", text: String(data) });
      }
      if (error) log({ type: "error", text: error });
    }
    prevLoadingRef.current = loading;
  }, [loading, data, error]);`;

  const paramsJsx = hasParams
    ? `
        {/* param inputs */}
        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "10px" }}>
${fn.inputs!
  .map(
    (i) => `          <div style={{ display: "flex", flexDirection: "column", gap: "4px", flex: 1, minWidth: "120px" }}>
            <label style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#52525b", letterSpacing: "0.06em" }}>
              ${i.name}&nbsp;<span style={{ color: "#3f3f46" }}>${shortType(i.type)}</span>
            </label>
            <input
              value={${toCamel(i.name)}}
              onChange={(e) => set${toPascal(i.name)}(e.target.value)}
              placeholder="${i.name}"
              onKeyDown={(e) => e.key === "Enter" && handleRefetch()}
              style={inputStyle}
            />
          </div>`
  )
  .join("\n")}
          <button onClick={handleRefetch} style={{ ...ghostBtnStyle, alignSelf: "flex-end", marginBottom: "0" }}>
            run
          </button>
        </div>`
    : "";

  return `
function ${toPascal(fn.name)}Row() {
  const log = useLog();
  const { data, loading, error, refetch } = ${hook}(${hookCall});
${stateDecls ? stateDecls + "\n" : ""}${logSetup}

  return (
    <div style={rowStyle}>
      {/* row header */}
      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
        <span style={fnNameStyle}>${fn.name}</span>
        <span style={readBadgeStyle}>view</span>

        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: "8px" }}>
          {/* inline result for no-param reads */}
          {!loading && data !== null && data !== undefined && (
            <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "11px", color: "#a1a1aa", maxWidth: "220px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              {String(data)}
            </span>
          )}
          {loading && <span style={{ fontSize: "11px", color: "#3f3f46" }}>…</span>}
          {error && <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#f87171" }} title={error}>error</span>}
          <button onClick={handleRefetch} style={refreshBtnStyle} title="Refresh">
            ↻
          </button>
        </div>
      </div>
${paramsJsx}
    </div>
  );
}`;
}

function buildWriteSection(fn: AbiEntry, contractName: string): string {
  const pascal = toPascal(contractName);
  const hook = `use${pascal}${toPascal(fn.name)}`;

  const stateDecls =
    fn.inputs?.length
      ? fn.inputs
          .map(
            (i) =>
              `  const [${toCamel(i.name)}, set${toPascal(i.name)}] = useState("");`
          )
          .join("\n")
      : "";

  const executeArgs = fn.inputs?.length
    ? fn.inputs.map((i) => toCamel(i.name)).join(", ")
    : "";

  const logCallText = fn.inputs?.length
    ? `${fn.name}(\${[${fn.inputs.map((i) => toCamel(i.name)).join(", ")}].join(", ")})`
    : `${fn.name}()`;

  const logSetup = `
  const prevStatusRef = useRef(status);
  useEffect(() => {
    if (prevStatusRef.current === status) return;
    prevStatusRef.current = status;
    if (status === "success" && txHash) log({ type: "tx", text: txHash });
    if (status === "error" && error) log({ type: "error", text: error });
  }, [status, txHash, error]);

  const handleExecute = useCallback(() => {
    log({ type: "call", text: \`${logCallText}\` });
    execute(${executeArgs});
  }, [execute, ${fn.inputs?.length ? fn.inputs.map((i) => toCamel(i.name)).join(", ") + ", " : ""}log]);`;

  const paramsJsx =
    fn.inputs?.length
      ? `
        {/* inputs + button on same row when possible */}
        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", alignItems: "flex-end", marginTop: "10px" }}>
${fn.inputs
  .map(
    (i) => `          <div style={{ display: "flex", flexDirection: "column", gap: "4px", flex: 1, minWidth: "120px" }}>
            <label style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#52525b", letterSpacing: "0.06em" }}>
              ${i.name}&nbsp;<span style={{ color: "#3f3f46" }}>${shortType(i.type)}</span>
            </label>
            <input
              value={${toCamel(i.name)}}
              onChange={(e) => set${toPascal(i.name)}(e.target.value)}
              placeholder="${i.name}"
              onKeyDown={(e) => e.key === "Enter" && !isDisabled && handleExecute()}
              style={inputStyle}
            />
          </div>`
  )
  .join("\n")}
          <div style={{ position: "relative" }} className="exec-wrap">
            <button
              onClick={handleExecute}
              disabled={isDisabled}
              style={{
                ...execBtnStyle,
                opacity: isDisabled ? 0.35 : 1,
                cursor: isDisabled ? "not-allowed" : "pointer",
              }}
            >
              {isPending ? "…" : "↗ execute"}
            </button>
            {!address && (
              <div className="exec-tooltip">connect wallet to execute</div>
            )}
          </div>
        </div>`
      : `
        <div style={{ marginTop: "10px", position: "relative" }} className="exec-wrap">
          <button
            onClick={handleExecute}
            disabled={isDisabled}
            style={{
              ...execBtnStyle,
              opacity: isDisabled ? 0.35 : 1,
              cursor: isDisabled ? "not-allowed" : "pointer",
            }}
          >
            {isPending ? "…" : "↗ execute"}
          </button>
          {!address && (
            <div className="exec-tooltip">connect wallet to execute</div>
          )}
        </div>`;

  return `
function ${toPascal(fn.name)}Row() {
  const log = useLog();
  const { execute, status, txHash, error, reset } = ${hook}();
  const { address } = useStarkzap();
${stateDecls ? stateDecls + "\n" : ""}
  const isPending = status === "pending";
  const isDisabled = !address || isPending;
${logSetup}

  return (
    <div style={rowStyle}>
      {/* row header */}
      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
        <span style={fnNameStyle}>${fn.name}</span>
        <span style={writeBadgeStyle}>external</span>
        {txHash && (
          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: "6px" }}>
            <span style={{ width: "5px", height: "5px", borderRadius: "50%", backgroundColor: "#4ade80" }} />
            <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#4ade8099", maxWidth: "160px", overflow: "hidden", textOverflow: "ellipsis" }}>
              {txHash.slice(0, 18)}…
            </span>
            <button onClick={reset} style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#3f3f46", background: "none", border: "none", cursor: "pointer", padding: "0" }}>
              ✕
            </button>
          </div>
        )}
        {error && !txHash && (
          <span style={{ marginLeft: "auto", fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#f87171" }} title={error}>
            error
          </span>
        )}
      </div>
${paramsJsx}
    </div>
  );
}`;
}

export function generateContractUI(
  contractName: string,
  parsed: ParsedAbi
): string {
  const pascal = toPascal(contractName);

  const readImports = parsed.reads.map(
    (fn) => `use${pascal}${toPascal(fn.name)}`
  );
  const writeImports = parsed.writes.map(
    (fn) => `use${pascal}${toPascal(fn.name)}`
  );
  const needsStarkzap = parsed.writes.length > 0;
  const allImports = [
    ...readImports,
    ...writeImports,
    ...(needsStarkzap ? ["useStarkzap"] : []),
  ];

  const readSections = parsed.reads.map((fn) =>
    buildReadSection(fn, contractName)
  );
  const writeSections = parsed.writes.map((fn) =>
    buildWriteSection(fn, contractName)
  );

  const readRender = parsed.reads.map(
    (fn) => `      <${toPascal(fn.name)}Row />`
  );
  const writeRender = parsed.writes.map(
    (fn) => `      <${toPascal(fn.name)}Row />`
  );

  const hasReads = parsed.reads.length > 0;
  const hasWrites = parsed.writes.length > 0;

  return `"use client";

import { useState, useCallback, useEffect, useRef, createContext, useContext } from "react";
import {
  ${allImports.join(",\n  ")},
} from "@/hooks/use${pascal}";
import type { LogEntry } from "@/components/LogsPanel";

// ── log context ────────────────────────────────────────────────────────────────
// Sections use this to emit log entries. ContractUI provides it via onLog prop.

type LogFn = (entry: Omit<LogEntry, "id" | "timestamp">) => void;
const LogContext = createContext<LogFn>(() => {});
const useLog = () => useContext(LogContext);

// ── shared styles ──────────────────────────────────────────────────────────────
// Defined once, used across all section rows.

const rowStyle: React.CSSProperties = {
  borderBottom: "1px solid #1a1a1a",
  padding: "10px 16px",
};

const fnNameStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "12px",
  fontWeight: 500,
  color: "#d4d4d8",
};

const readBadgeStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "10px",
  color: "#4ade8066",
  border: "1px solid #1a3a1a",
  borderRadius: "3px",
  padding: "1px 6px",
  letterSpacing: "0.04em",
};

const writeBadgeStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "10px",
  color: "#f59e0b99",
  border: "1px solid #3a2a0a",
  borderRadius: "3px",
  padding: "1px 6px",
  letterSpacing: "0.04em",
};

const inputStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "12px",
  color: "#d4d4d8",
  backgroundColor: "#0f0f0f",
  border: "1px solid #2a2a2a",
  borderRadius: "4px",
  padding: "5px 10px",
  outline: "none",
  width: "100%",
};

const refreshBtnStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "13px",
  color: "#3f3f46",
  background: "none",
  border: "none",
  cursor: "pointer",
  padding: "0 2px",
  lineHeight: 1,
  transition: "color 0.1s",
};

const ghostBtnStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "11px",
  color: "#52525b",
  background: "none",
  border: "1px solid #2a2a2a",
  borderRadius: "4px",
  padding: "5px 12px",
  cursor: "pointer",
  whiteSpace: "nowrap",
  transition: "border-color 0.15s, color 0.15s",
};

const execBtnStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: "11px",
  color: "#f59e0b",
  background: "none",
  border: "1px solid #3a2a0a",
  borderRadius: "4px",
  padding: "5px 14px",
  transition: "border-color 0.15s, color 0.15s",
  whiteSpace: "nowrap",
};

// ── section rows (generated from ABI) ─────────────────────────────────────────
${readSections.join("\n")}
${writeSections.join("\n")}

// ── main export ────────────────────────────────────────────────────────────────

export function ContractUI({ onLog }: { onLog?: LogFn }) {
  ${needsStarkzap ? "const { address } = useStarkzap();" : ""}

  return (
    <LogContext.Provider value={onLog ?? (() => {})}>
      {/* tooltip CSS — scoped here to avoid polluting globals */}
      <style>{\`
        .exec-wrap { display: inline-block; }
        .exec-tooltip {
          position: absolute;
          bottom: calc(100% + 6px);
          left: 50%;
          transform: translateX(-50%);
          white-space: nowrap;
          background: #141414;
          border: 1px solid #2a2a2a;
          border-radius: 4px;
          padding: 3px 8px;
          font-family: ui-monospace, monospace;
          font-size: 10px;
          color: #71717a;
          pointer-events: none;
          opacity: 0;
          transition: opacity 0.15s;
        }
        .exec-wrap:hover .exec-tooltip { opacity: 1; }
      \`}</style>

      <div style={{ border: "1px solid #1e1e1e", borderRadius: "6px", overflow: "hidden" }}>
${
  hasReads
    ? `        {/* ── Read ──────────────────────────────────────────────────────────── */}
        <div style={{ padding: "6px 16px 5px", backgroundColor: "#0d0d0d", borderBottom: "1px solid #1a1a1a" }}>
          <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.14em", color: "#3f3f46" }}>
            read
          </span>
        </div>
${readRender.join("\n")}`
    : ""
}
${
  hasWrites
    ? `
        {/* ── Write ─────────────────────────────────────────────────────────── */}
        <div style={{ padding: "6px 16px 5px", backgroundColor: "#0d0d0d", borderBottom: "1px solid #1a1a1a", borderTop: "${hasReads ? "1px solid #1e1e1e" : "none"}", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.14em", color: "#3f3f46" }}>
            write
          </span>
          {/* ONE wallet hint — not repeated per function */}
          {!address && (
            <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "10px", color: "#3f3f46" }}>
              connect wallet to enable write operations
            </span>
          )}
        </div>
${writeRender.join("\n")}`
    : ""
}
${!hasReads && !hasWrites ? `        <div style={{ padding: "24px 16px" }}><span style={{ fontFamily: "ui-monospace, monospace", fontSize: "12px", color: "#3f3f46" }}>No public functions in this ABI.</span></div>` : ""}
      </div>
    </LogContext.Provider>
  );
}
`;
}

// ── README.md ──────────────────────────────────────────────────────────────────

export function generateReadme(
  contractName: string,
  contractAddress: string,
  classHash: string,
  network: string,
  parsed: ParsedAbi
): string {
  const readList =
    parsed.reads.map((fn) => `- \`${fn.name}\` — view`).join("\n") ||
    "_none_";
  const writeList =
    parsed.writes
      .map((fn) => `- \`${fn.name}\` — external (gasless ⚡)`)
      .join("\n") || "_none_";
  const pascal = toPascal(contractName);
  const firstWrite = parsed.writes[0];

  return `# ${contractName}

Generated by [Unzap Contract Lab](https://unzap.dev).

## Quick start

\`\`\`bash
npm install
cp .env.example .env.local
npm run dev
\`\`\`

## Contract

| | |
|---|---|
| **Address** | \`${contractAddress}\` |
| **Class** | \`${classHash}\` |
| **Network** | Starknet ${network} |

## ABI

**Read**
${readList}

**Write**
${writeList}

## Layout

\`\`\`
app/
  layout.tsx              StarkzapProvider (wallet singleton)
  page.tsx                TopBar + ContractUI + LogsPanel
  globals.css             Tailwind v4 base
components/
  ContractUI.tsx          ABI-driven interaction panel
  LogsPanel.tsx           Terminal output panel
hooks/
  use${pascal}.ts         Generated hooks + StarkzapProvider
lib/
  contract.ts             Address, ABI, network constants
\`\`\`
${
  firstWrite
    ? `
## Write hooks

Transactions route through [Starkzap](https://github.com/keep-starknet-strange/starkzap) with AVNU paymaster — no gas required.

\`\`\`tsx
import { use${pascal}${toPascal(firstWrite.name)} } from "@/hooks/use${pascal}";

const { execute, status, txHash } = use${pascal}${toPascal(firstWrite.name)}();
\`\`\``
    : ""
}
`;
}
